name:                durc-api
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/durc-api#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web
extra-source-files:
- README.md

default-extensions:
  - AllowAmbiguousTypes
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PackageImports
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall
  - -Werror
  - -Wredundant-constraints
  - -fwarn-tabs
  - -threaded
  - -O2
  - -rtsopts
  - -with-rtsopts=-N
  - -with-rtsopts=-T

dependencies:
  - aeson
  - base
  - basic-prelude
  - bytestring
  - containers
  - lens
  - servant
  - servant-server
  - servant-client
  - servant-client-core
  - time
  - text
  - unordered-containers
  - QuickCheck

library:
  source-dirs:      src
    
